/**
 * Core domain types for the EcoLens application.
 * @module types
 */

/** The four supported emission tracking categories. */
export type Category = 'transport' | 'food' | 'energy' | 'shopping';

/**
 * A single logged activity with its calculated carbon emission.
 * Stored in Firestore under `users/{uid}/activities/{id}`.
 */
export interface Activity {
  /** Unique identifier (client-generated). */
  id: string;
  /** Firebase Auth UID of the owning user. */
  userId?: string;
  /** Emission category this activity belongs to. */
  category: Category;
  /** Specific activity type key (e.g. 'car_petrol', 'beef_meal'). */
  subType: string;
  /** Numeric amount of the activity performed. */
  quantity: number;
  /** Unit of measurement (e.g. 'km', 'kWh', 'serving'). */
  unit: string;
  /** Calculated CO₂ equivalent emission in kilograms. */
  co2e_kg: number;
  /** ISO 8601 timestamp of when the activity was logged. */
  timestamp: string;
  /** Optional user note describing context. */
  note: string;
}

/**
 * A personalised reduction tip generated by Gemini AI.
 * Returned as part of the AI insights feature.
 */
export interface Insight {
  /** Short title for the tip (max 8 words). */
  title: string;
  /** Detailed explanation of the suggestion (max 60 words). */
  description: string;
  /** Estimated monthly CO₂e saving in kg if tip is followed. */
  saving_kg: number;
  /** Category this insight relates to. */
  category: Category;
  /** Single emoji icon representing the insight visually. */
  icon: string;
}

/**
 * An eco challenge that users can complete to reduce their footprint.
 * Completion state is persisted per-user in Firestore.
 */
export interface Challenge {
  /** Unique challenge identifier (slug format). */
  id: string;
  /** Human-readable challenge name. */
  title: string;
  /** Detailed description of what the challenge entails. */
  description: string;
  /** Estimated CO₂e saving on completion (kg). */
  estimated_saving_kg: number;
  /** Duration of the challenge in days. */
  duration_days: number;
  /** Category this challenge targets. */
  category: Category;
  /** Whether the user has completed this challenge. */
  completed: boolean;
}

/**
 * Aggregated emission summary for a time period (typically 7 days).
 * Used by the dashboard and AI insights features.
 */
export interface EmissionSummary {
  /** Total emissions across all categories (kg CO₂e). */
  total_kg: number;
  /** Transport category subtotal (kg CO₂e). */
  transport_kg: number;
  /** Food category subtotal (kg CO₂e). */
  food_kg: number;
  /** Energy category subtotal (kg CO₂e). */
  energy_kg: number;
  /** Shopping category subtotal (kg CO₂e). */
  shopping_kg: number;
  /** Description of the highest single emission activity. */
  top_activity: string;
}
